import { BbsEntry } from "./types";

export const DEFAULT_PHONEBOOK: BbsEntry[] = [
  // --- Featured ---
  {
    id: "phosphor-bbs",
    name: "Phosphor BBS",
    host: "136.117.127.123",
    port: 8888,
    encoding: "utf8",
    protocol: "telnet",
    description: "The MacOS BBS Client's home base",
    category: "Featured",
  },
  {
    id: "ptt",
    name: "PTT",
    host: "ptt.cc",
    port: 22,
    encoding: "utf8",
    protocol: "ssh",
    username: "bbsu",
    description: "Taiwan's largest BBS",
    category: "Featured",
  },
  {
    id: "blackflag",
    name: "Black Flag",
    host: "blackflag.acid.org",
    port: 23,
    encoding: "utf8",
    protocol: "telnet",
    description: "ACiD artscene since 1995",
    category: "Featured",
  },
  {
    id: "level29",
    name: "Level 29",
    host: "bbs.fozztexx.com",
    port: 23,
    encoding: "utf8",
    protocol: "telnet",
    description: "Retro computing, 6 nodes",
    category: "Featured",
  },
  {
    id: "vertrauen",
    name: "Vertrauen",
    host: "vert.synchro.net",
    port: 23,
    encoding: "utf8",
    protocol: "telnet",
    description: "Original Synchronet BBS",
    category: "Featured",
  },

  // --- Artscene ---
  {
    id: "distortion",
    name: "Distortion",
    host: "d1st.org",
    port: 23,
    encoding: "utf8",
    protocol: "telnet",
    description: "ANSI/ASCII art + modding",
    category: "Artscene",
  },
  {
    id: "bodax",
    name: "BodaX",
    host: "bbs.beardy.se",
    port: 23,
    encoding: "utf8",
    protocol: "telnet",
    description: "ENiGMA½, multiple networks",
    category: "Artscene",
  },

  // --- Door Games ---
  {
    id: "dgu",
    name: "Door Games Unlimited",
    host: "dgu.strangled.net",
    port: 23,
    encoding: "utf8",
    protocol: "telnet",
    description: "500+ door games",
    category: "Door Games",
  },
  {
    id: "32bit",
    name: "32-Bit BBS",
    host: "x-bit.org",
    port: 23230,
    encoding: "utf8",
    protocol: "telnet",
    description: "Last Spitfire BBS on earth",
    category: "Door Games",
  },
  {
    id: "anet",
    name: "A-Net Online",
    host: "a-net.online",
    port: 23,
    encoding: "utf8",
    protocol: "telnet",
    description: "Est. 1996, 600+ games",
    category: "Door Games",
  },

  // --- Community ---
  {
    id: "20forbeers",
    name: "20 For Beers",
    host: "20forbeers.com",
    port: 1337,
    encoding: "utf8",
    protocol: "telnet",
    description: "Active Amiga scene",
    category: "Community",
  },
  {
    id: "alsgeeklab",
    name: "Al's Geek Lab",
    host: "bbs.alsgeeklab.com",
    port: 2323,
    encoding: "utf8",
    protocol: "telnet",
    description: "YouTube BBS creator",
    category: "Community",
  },
  {
    id: "absinthe",
    name: "Absinthe",
    host: "absinthebbs.net",
    port: 1940,
    encoding: "utf8",
    protocol: "telnet",
    description: "Thriving C-Net community",
    category: "Community",
  },
  {
    id: "bottomless",
    name: "Bottomless Abyss",
    host: "bbs.bottomlessabyss.net",
    port: 2023,
    encoding: "utf8",
    protocol: "telnet",
    description: "Privacy-focused, CTF",
    category: "Community",
  },
  {
    id: "agency",
    name: "Agency BBS",
    host: "agency.bbs.nz",
    port: 23,
    encoding: "utf8",
    protocol: "telnet",
    description: "New Zealand, since 1993",
    category: "Community",
  },

  // --- Vintage Hardware ---
  {
    id: "particles",
    name: "Particles!",
    host: "particlesbbs.dyndns.org",
    port: 6400,
    encoding: "utf8",
    protocol: "telnet",
    description: "Runs on Commodore 128",
    category: "Vintage",
  },
  {
    id: "dura",
    name: "Dura-Europos",
    host: "dura-bbs.net",
    port: 6359,
    encoding: "utf8",
    protocol: "telnet",
    description: "Runs on Apple IIe",
    category: "Vintage",
  },

  // --- Taiwan ---
  {
    id: "ptt2",
    name: "PTT2",
    host: "ptt2.cc",
    port: 23,
    encoding: "utf8",
    protocol: "telnet",
    description: "PTT sister board",
    category: "Taiwan",
  },
  {
    id: "bahamut",
    name: "Bahamut",
    host: "bbs.gamer.com.tw",
    port: 23,
    encoding: "big5",
    protocol: "telnet",
    description: "Taiwan gaming community",
    category: "Taiwan",
  },
];
